# Generated by Django 5.2.8 on 2025-11-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the todo item', max_length=200)),
                ('due_date', models.DateField(blank=True, help_text='Due date for the todo', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the todo is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the todo was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the todo was last updated')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
